### ISSUE TITLE
Uncaught Error: Cannot find module "funnies/react"

### ISSUE THREAD

**Issue by gazpachu** [1egoman/funnies#107]
I think the react example is wrong.

**Comment by 1egoman** [comment]
@gazpachu gazpachu Can you provide more of a stack trace I think it may actually be `require("funnies/dist/react")` but before making the update want to make sure that I understand what you're doing.

**Comment by gazpachu** [comment]
Yeah, probably `import Funnies from 'funnies/dist/react'; should fix it but at the end, I had to copy the messages into my app to make them work
