### ISSUE TITLE
Any desire to update the React component + testing?

### ISSUE THREAD

**Issue by justinzelinsky** [1egoman/funnies#120]
Cute project! I took a look at the React component and testing and I was wondering if you had any interesting updating it to be a functional component with hooks and to update the testing to use jest and snapshot tests?

**Comment by 1egoman** [comment]
Unfortunately, I don't really have time to do it, no. If you or someone else would be willing then I'd accept a pull request!

**Comment by ghost** [comment]
I'll take a stab at it myself! Cheers!
