### ISSUE TITLE
Gulp watch task

### ISSUE THREAD

**Issue by 1egoman** [1egoman/funnies#45]
There currently isn't a good way to build funnies in the background as one works. Ideally, we'd have a workflow where one runs `gulp watch` and as gulp sees changes to the filesystem it would automatically build any changes.

What's involved:
- Add a gulp task called `watch` that when invoked watches for filesystem changes and rebuilds.
- Use something like `watchify` to take advantage of delta updates to make the build process happen faster.

Thanks for taking a look!

**Comment by andela-rekemezie** [comment]
@1egoman Is this task open?

**Comment by 1egoman** [comment]
@andela-rekemezie It is!

**Comment by vincealdrin** [comment]
Can I still work on this?

**Comment by 1egoman** [comment]
@vincealdrin As far as I know, nobody's started this yet. Feel free to take a crack at it.
